In [5]:
import pandas as pd

In [6]:
import warnings 
warnings.filterwarnings("ignore")

In [7]:
#load data
data=pd.read_csv("creditcard.csv")

# Data Preprocessing

In [8]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0


In [9]:
data.shape

(284807, 31)

In [10]:
data.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [12]:
data.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [13]:
data.duplicated().sum()

np.int64(1081)

In [14]:
data.drop_duplicates(inplace=True,ignore_index=True)  #ignore index can resets the index of the dataframe

In [15]:
data.corr()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
Time,1.000000,0.117927,-0.010556,-0.422054,-0.105845,0.173223,-0.063279,0.085335,-0.038203,-0.007861,...,0.045913,0.143727,0.051474,-0.015954,-0.233262,-0.041818,-0.005171,-0.009305,-0.010559,-0.012359
V1,0.117927,1.000000,0.006875,-0.008112,0.002257,-0.007036,0.000413,-0.009173,-0.001168,0.001828,...,0.002818,-0.001436,-0.001330,-0.000723,-0.000222,-0.000684,-0.015706,-0.004861,-0.230105,-0.094486
V2,-0.010556,0.006875,1.000000,0.005278,-0.001495,0.005210,-0.000594,0.007425,0.002899,-0.000274,...,-0.004897,0.001237,-0.003855,0.000701,-0.001569,0.000253,0.007555,0.001611,-0.533428,0.084624
V3,-0.422054,-0.008112,0.005278,1.000000,0.002829,-0.006879,-0.001511,-0.011721,-0.001815,-0.003579,...,0.003500,-0.000275,0.000449,-0.000072,0.000425,-0.000094,-0.007051,-0.000134,-0.212410,-0.182322
V4,-0.105845,0.002257,-0.001495,0.002829,1.000000,0.001744,-0.000880,0.004657,0.000890,0.002154,...,-0.001034,0.000115,0.000732,-0.000120,0.000162,0.000777,0.001322,0.000231,0.099514,0.129326
V5,0.173223,-0.007036,0.005210,-0.006879,0.001744,1.000000,-0.000938,-0.008709,0.001430,-0.001213,...,0.001622,-0.000559,0.001183,0.000198,0.000069,0.000390,-0.005798,-0.000820,-0.387685,-0.087812
V6,-0.063279,0.000413,-0.000594,-0.001511,-0.000880,-0.000938,1.000000,0.000436,0.003036,-0.000734,...,-0.002134,0.001104,-0.000755,0.001202,0.000697,-0.000028,0.000289,0.000925,0.216389,-0.043915
V7,0.085335,-0.009173,0.007425,-0.011721,0.004657,-0.008709,0.000436,1.000000,-0.006419,-0.004921,...,0.009010,-0.002280,0.003303,-0.000384,-0.000072,0.000624,-0.004537,0.001657,0.400408,-0.172347
V8,-0.038203,-0.001168,0.002899,-0.001815,0.000890,0.001430,0.003036,-0.006419,1.000000,0.001038,...,0.018892,-0.006156,0.004994,0.000113,0.000011,-0.001407,0.000613,-0.000099,-0.104662,0.033068
V9,-0.007861,0.001828,-0.000274,-0.003579,0.002154,-0.001213,-0.000734,-0.004921,0.001038,1.000000,...,0.000679,0.000785,0.000677,-0.000103,-0.000275,0.001253,0.008221,0.005591,-0.044123,-0.094021


In [16]:
#breaking our data into X and y
X=data.drop("Class",axis=1)
y=data.Class

In [17]:
y.value_counts()

Class
0    283253
1       473
Name: count, dtype: int64

In [18]:
#Lets we can train-test split our Data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=123)

## Data Balancing

In [19]:
#Lets we can use the SMOTE
from imblearn.over_sampling import SMOTE
smote=SMOTE(sampling_strategy="minority",random_state=0)

In [20]:
X_train,y_train=smote.fit_resample(X_train,y_train)

In [21]:
X_train.shape

(424890, 30)

In [22]:
y_train.value_counts()

Class
0    212445
1    212445
Name: count, dtype: int64

In [23]:
X_train,X_val,y_train,y_val=train_test_split(X_train,y_train,test_size=0.20,stratify=y_train,random_state=42)  #stratify=y_train means that make the proportion of test(validation) ,according to the proportion of y_train. 

## Apply Normalization and Standardization Scaling On our Data

In [24]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [25]:
#Normalization
mmscaler=MinMaxScaler()
mmscaled_train=mmscaler.fit_transform(X_train)
mmscaled_test=mmscaler.transform(X_test)

In [26]:
#Standardization
stscaler=StandardScaler()
stscaled_train=stscaler.fit_transform(X_train)
stscaled_val=stscaler.transform(X_val)
stscaled_test=stscaler.transform(X_test)

# Applying Our ANN Model

In [27]:
#Importing Libraries
from tensorflow import keras
from keras import layers

In [28]:
# model_ar=keras.Sequential([
#     layers.Input(shape=(X_train.shape[1],)),  #Or (30,)
#     layers.Dense(32,activation="relu"),
#     layers.Dense(16,activation="relu"),
#     layers.Dense(1,activation="sigmoid")

# ])

In [29]:
# model_ar.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy","precision","recall"])

In [30]:
def create_model(activation, optimizer):
    model = keras.Sequential([
        layers.Input((X_train.shape[-1],)),
        layers.Dense(64,activation=activation),
        layers.Dense(32, activation=activation),
        layers.Dense(16, activation=activation),
        layers.Dense(8,activation=activation),
        layers.Dense(1, activation="sigmoid")
    ])

    model.compile(
        optimizer=optimizer,
        loss="binary_crossentropy",
        metrics=["accuracy","precision","recall"]
    )

    return model

In [31]:
#model_ar.fit(stscaled_train,y_train,epochs=20,validation_split=0.20,batch_size=128)
#model_ar.fit(stscaled_train,y_train,epochs=50,validation_split=0.20,batch_size=128)
# model_ar.fit(stscaled_train,y_train,epochs=100,validation_split=0.20,batch_size=128)

## Model1 Fitting 

In [32]:
# model1_20 = create_model("relu", "adam")

# model1_20.fit(
#     stscaled_train,
#     y_train,
#     epochs=20,
#     validation_data=(stscaled_val,y_val),
#     batch_size=128
# )

In [33]:
model1_50 = create_model("relu", "adam")

model1_50.fit(
    stscaled_train,
    y_train,
    epochs=50,
    validation_data=(stscaled_val,y_val),
    batch_size=128

)

Epoch 1/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.9881 - loss: 0.0355 - precision: 0.9921 - recall: 0.9841 - val_accuracy: 0.9980 - val_loss: 0.0075 - val_precision: 0.9962 - val_recall: 0.9998
Epoch 2/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9985 - loss: 0.0057 - precision: 0.9979 - recall: 0.9991 - val_accuracy: 0.9991 - val_loss: 0.0034 - val_precision: 0.9982 - val_recall: 1.0000
Epoch 3/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9990 - loss: 0.0040 - precision: 0.9985 - recall: 0.9994 - val_accuracy: 0.9989 - val_loss: 0.0039 - val_precision: 0.9987 - val_recall: 0.9992
Epoch 4/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9991 - loss: 0.0034 - precision: 0.9988 - recall: 0.9995 - val_accuracy: 0.9989 - val_loss: 0.0041 - val_precision: 0.9979 - val_recall: 1.0000
Epoch 5/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9992 - loss: 0.0030 - precision: 0.9989 - recall: 0.9995 - val_accuracy: 0.9993 - v

## Model2 Fiting 

In [42]:
model2_50 = create_model("tanh", "sgd")

model2_50.fit(
    stscaled_train,
    y_train,
    epochs=50,
    validation_data=(stscaled_val,y_val),
    batch_size=128

)

Epoch 1/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - accuracy: 0.9580 - loss: 0.1204 - precision: 0.9786 - recall: 0.9364 - val_accuracy: 0.9724 - val_loss: 0.0761 - val_precision: 0.9822 - val_recall: 0.9622
Epoch 2/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9775 - loss: 0.0639 - precision: 0.9838 - recall: 0.9710 - val_accuracy: 0.9815 - val_loss: 0.0530 - val_precision: 0.9858 - val_recall: 0.9771
Epoch 3/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9839 - loss: 0.0458 - precision: 0.9879 - recall: 0.9798 - val_accuracy: 0.9870 - val_loss: 0.0385 - val_precision: 0.9890 - val_recall: 0.9850
Epoch 4/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9883 - loss: 0.0334 - precision: 0.9906 - recall: 0.9860 - val_accuracy: 0.9911 - val_loss: 0.0285 - val_precision: 0.9907 - val_recall: 0.9916
Epoch 5/50
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9918 - loss: 0.0250 - precision: 0.9926 - recall: 0.9910 - val_accuracy: 0.9936

## Model 3 Fitting

In [43]:
model3_100 = create_model("relu","rmsprop")

model3_100.fit(
    stscaled_train,
    y_train,
    epochs=100,
    validation_data=(stscaled_val,y_val),
    batch_size=128

)

Epoch 1/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - accuracy: 0.9896 - loss: 0.0323 - precision: 0.9935 - recall: 0.9856 - val_accuracy: 0.9973 - val_loss: 0.0088 - val_precision: 0.9977 - val_recall: 0.9970
Epoch 2/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9982 - loss: 0.0072 - precision: 0.9975 - recall: 0.9989 - val_accuracy: 0.9991 - val_loss: 0.0049 - val_precision: 0.9987 - val_recall: 0.9994
Epoch 3/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9987 - loss: 0.0053 - precision: 0.9982 - recall: 0.9992 - val_accuracy: 0.9990 - val_loss: 0.0048 - val_precision: 0.9979 - val_recall: 1.0000
Epoch 4/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9989 - loss: 0.0045 - precision: 0.9985 - recall: 0.9994 - val_accuracy: 0.9987 - val_loss: 0.0053 - val_precision: 0.9990 - val_recall: 0.9984
Epoch 5/100
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - accuracy: 0.9990 - loss: 0.0042 - precision: 0.9987 - recall: 0.9994 - val_accuracy: 0

## Model 4 Fitting 

In [67]:
model4 = create_model("tanh","adam")

model4.fit(
    stscaled_train,
    y_train,
    epochs=30,
    validation_data=(stscaled_val,y_val),
    batch_size=128

)

Epoch 1/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - accuracy: 0.9853 - loss: 0.0413 - precision: 0.9891 - recall: 0.9814 - val_accuracy: 0.9931 - val_loss: 0.0199 - val_precision: 0.9929 - val_recall: 0.9932
Epoch 2/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9973 - loss: 0.0091 - precision: 0.9964 - recall: 0.9981 - val_accuracy: 0.9980 - val_loss: 0.0070 - val_precision: 0.9968 - val_recall: 0.9992
Epoch 3/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9984 - loss: 0.0058 - precision: 0.9978 - recall: 0.9990 - val_accuracy: 0.9989 - val_loss: 0.0050 - val_precision: 0.9978 - val_recall: 1.0000
Epoch 4/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9987 - loss: 0.0048 - precision: 0.9982 - recall: 0.9992 - val_accuracy: 0.9992 - val_loss: 0.0038 - val_precision: 0.9984 - val_recall: 1.0000
Epoch 5/30
2656/2656 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - accuracy: 0.9992 - loss: 0.0035 - precision: 0.9988 - recall: 0.9995 - val_accuracy: 0.9993

model_ar,adam,batch_size=64

In [61]:
#Epoch 20/20
#5312/5312 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9996 - loss: 0.0013 - precision: 0.9992 - recall: 0.9997 - val_accuracy: 1.0000 - val_loss: 3.5467e-04 - val_precision: 1.0000 - val_recall: 1.0000

model_ar,adam,batch_size=128

In [62]:
#Epoch 20/20
#2656/2656 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9999 - loss: 4.6336e-04 - precision: 0.9998 - recall: 0.9999 - val_accuracy: 1.0000 - val_loss: 8.6220e-05 - val_precision: 1.0000 - val_recall: 1.0000

model_ar,adam,batch_size=256

In [63]:
#Epoch 20/20
#1328/1328 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9999 - loss: 2.3872e-04 - precision: 0.9999 - recall: 0.9999 - val_accuracy: 0.9996 - val_loss: 0.0011 - val_precision: 1.0000 - val_recall: 0.9996

Lets the best results,according to the val_accuracy and others with relation to the training accuracy,The best batch size is 128 for this model.

## Model prediction on unseen(test) Data

#### Predictions For Model 1

In [64]:
# y_pred1_20=model1_20.predict(stscaled_test)
# y_pred1_20=(y_pred1_20 >=0.5).astype(int).ravel()   #astype(int) can converts it to 0 and 1 ,and ravel can convert it into 1D array

#It exactly like this
#y_pred = [1 if prob[0] >= 0.5 else 0 for p in y_pred1_20]
#prob[0] can picks our number at there
# prob       → [0.23]
# prob[0]    → 0.23

In [49]:
y_pred1_50=model1_50.predict(stscaled_test)
y_pred1_50=(y_pred1_50 >=0.6).astype(int).ravel()

# y_prob = model1_50.predict(stscaled_test).ravel()

# for threshold in [0.3, 0.4, 0.5, 0.6, 0.7]:
#     y_pred = (y_prob >= threshold).astype(int)

#     print("Threshold:", threshold)
#     print("Precision:", precision_score(y_test, y_pred, zero_division=0))
#     print("Recall:", recall_score(y_test, y_pred, zero_division=0))
#     print("F1:", f1_score(y_test, y_pred, zero_division=0))
#     print()

2217/2217 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step


#### Predictions For Model 2

In [50]:
y_pred2_50=model2_50.predict(stscaled_test)
y_pred2_50=(y_pred2_50 >= 0.6).astype(int).ravel()

2217/2217 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step


#### Predictions For Model 3

In [51]:
y_pred3_100=model3_100.predict(stscaled_test)
y_pred3_100=(y_pred3_100 >= 0.6).astype(int).ravel()

2217/2217 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step


### Predictions For Model 4

In [68]:
y_pred4=model4.predict(stscaled_test)
y_pred4=(y_pred4 >= 0.6).astype(int).ravel()

2217/2217 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step


## Finding confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

# For Model 1

In [54]:
#With 20 Epochs
# accuracy1_20 = accuracy_score(y_test, y_pred1_20)
# precision1_20 = precision_score(y_test, y_pred1_20)
# recall1_20 = recall_score(y_test, y_pred1_20)
# f1_1_20 = f1_score(y_test, y_pred1_20)
# confusion_matrix1_20=confusion_matrix(y_test,y_pred1_20)

In [55]:
#With 50 Epochs
accuracy1_50 = accuracy_score(y_test, y_pred1_50)
precision1_50 = precision_score(y_test, y_pred1_50)
recall1_50 = recall_score(y_test, y_pred1_50)
f1_1_50 = f1_score(y_test, y_pred1_50)
confusion_matrix1_50=confusion_matrix(y_test,y_pred1_50)

# For Model 2

In [56]:
#With 50 Epochs
accuracy2_50 = accuracy_score(y_test, y_pred2_50)
precision2_50 = precision_score(y_test, y_pred2_50)
recall2_50 = recall_score(y_test, y_pred2_50)
f1_2_50 = f1_score(y_test, y_pred2_50)
confusion_matrix2_50=confusion_matrix(y_test,y_pred2_50)

# For Model 3

In [57]:
#With 100 Epochs
accuracy3_100 = accuracy_score(y_test, y_pred3_100)
precision3_100 = precision_score(y_test, y_pred3_100)
recall3_100 = recall_score(y_test, y_pred3_100)
f1_3_100 = f1_score(y_test, y_pred3_100)
confusion_matrix3_100=confusion_matrix(y_test,y_pred3_100)

# Model 4

In [69]:
accuracy4 = accuracy_score(y_test, y_pred4)
precision4 = precision_score(y_test, y_pred4)
recall4 = recall_score(y_test, y_pred4)
f1_4 = f1_score(y_test, y_pred4)
confusion_matrix4=confusion_matrix(y_test,y_pred4)

### Models Results:

In [59]:
#Model 1
print(accuracy1_50)
print(precision1_50)
print(recall1_50)
print(f1_1_50)

0.9994078836068347
0.8203125
0.8467741935483871
0.8333333333333334


In [60]:
#model 1
print(confusion_matrix1_50)  #CONFUSION MATRIX

[[70785    23]
 [   19   105]]


In [61]:
#model 2 
print(accuracy2_50)
print(precision2_50)
print(recall2_50)
print(f1_2_50)

0.9986747871200586
0.5824175824175825
0.8548387096774194
0.6928104575163399


In [62]:
#model 2   #CONFUSION MATRIX
print(confusion_matrix2_50)

[[70732    76]
 [   18   106]]


In [63]:
#model 3
print(accuracy3_100)
print(precision3_100)
print(recall3_100)
print(f1_3_100)

0.99908362939153
0.7006802721088435
0.8306451612903226
0.7601476014760148


In [64]:
#Model 3    #CONFUSON MATRIX
print(confusion_matrix3_100)

[[70764    44]
 [   21   103]]


In [70]:
#Model 4
print(accuracy4)
print(precision4)
print(recall4)
print(f1_4)

0.999097727400891
0.6973684210526315
0.8548387096774194
0.7681159420289855


In [71]:
print(confusion_matrix4)

[[70762    46]
 [   18   106]]


## Models Comparasion Chart:

In [73]:
pd.DataFrame({"Model":["Model 1","Model 2","Model 3","Model 4"],"Activation":["Relu","Tanh","Relu","tanh"],"Optimizer":["Adam","SGD","RMSProp","adam"],"Epochs":[50,50,100,30],"Acuracy":[0.9994,0.9986,0.9984,0.9990],"Precision":[0.8203,0.5824,0.7006,0.6973],"Recall":[0.8467,0.8548,0.8306,0.8548],"F1_score":[0.8333,0.6928,0.7601,0.7681]})

,Model,Activation,Optimizer,Epochs,Acuracy,Precision,Recall,F1_score
0,Model 1,Relu,Adam,50,0.9994,0.8203,0.8467,0.8333
1,Model 2,Tanh,SGD,50,0.9986,0.5824,0.8548,0.6928
2,Model 3,Relu,RMSProp,100,0.9984,0.7006,0.8306,0.7601
3,Model 4,tanh,adam,30,0.9990,0.6973,0.8548,0.7681


### Prediction Samples

In [79]:
pd.DataFrame({"Actual":y_test[450:500],"Predicted":y_pred1_50[450:500]})

,Actual,Predicted
223600,0,0
140223,0,0
115516,0,0
154922,0,0
150901,0,0
12932,0,0
80171,0,0
71738,0,0
25274,0,0
183746,0,0


# Conclusion:

Model 1 (ReLU activation, Adam optimizer, 50 epochs) achieved the best overall performance, showing the highest accuracy (0.9994) and strong precision, recall, and F1 scores compared to the other models.
